version: 2.1

# define the jobs we want to run for this project
jobs:
  plan-apply:
    working_directory: ~/capstone/terraform
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout:
          path: ~/capstone
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file terraform.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
    
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            echo "Say apply to YAML!"
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-infra:
    working_directory: ~/capstone/sock-shop
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl deploy infrastructure
          command: |
            echo "deploy-infra to YAML!"
      - persist_to_workspace:
          root: .
          paths:
            - .

  teardown-infra:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl destroy infrastructure
          command: |
            echo "teardown-infra YAML!"
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-ingress:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl create ingress
          command: |
            echo "deploy-ingress YAML!"
      - persist_to_workspace:
          root: .
          paths:
            - .

  teardown-ingress:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl delete ingress
          command: |
            echo "teardown-ingress YAML!"
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tf
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

# orchestrate our job run sequence
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - deploy-infra:
          requires:
            - apply
      - teardown-infra:
          requires:
            - apply
            - deploy-infra
      - deploy-ingress:
          requires:
            - apply
            - deploy-infra
      - teardown-ingress:
          requires:
            - apply
            - deploy-ingress
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy