version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4

# define the jobs we want to run for this project
jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          parameters:
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-region: AWS_DEFAULT_REGION
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  plan-apply:
    working_directory: ~/capstone/
    # working_directory: ~/capstone/terraform
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout:
          path: ~/capstone
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file terraform.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
    
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
            
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  deploy-infra:
    # working_directory: ~/capstone/sock-shop
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl deploy infrastructure
          command: |
            kubectl apply -f complete-demo.yaml
      - persist_to_workspace:
          root: .
          paths:
            - .

  teardown-infra:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl destroy infrastructure
          command: |
            kubectl delete --all deployments --namespace=sock-shop
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-ingress:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl create ingress
          command: |
            kubectl config set-context --current --namespace=sock-shop
            kubectl create -f ingress.yml
      - persist_to_workspace:
          root: .
          paths:
            - .

  teardown-ingress:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: kubectl delete ingress
          command: |
            kubectl config set-context --current --namespace=sock-shop 
            kubectl delete -f ingress.yml
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tf
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

# orchestrate our job run sequence
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli:
          context: aws
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - deploy-infra:
          requires:
            - apply
      - teardown-infra:
          requires:
            - deploy-infra
      - deploy-ingress:
          requires:
            - deploy-infra
      - teardown-ingress:
          requires:
            - deploy-ingress
      - plan-destroy
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
            # - plan-apply
      - destroy:
          requires:
            - hold-destroy